ci: disable mingw32 for now
gst-plugins-goods and libusb seems to be missing:

```
  Enter a selection (default=all): error: target not found: mingw-w64-i686-gst-plugins-good
  error: target not found: mingw-w64-i686-libusb
```